### PR TITLE
static field for constant in SessionRepositoryFilter

### PR DESCRIPTION
**Pull request by panchenko**
Micro optimization: define constant as a static field.

Obvious Fix.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@panchenko Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=654)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-session&pullRequestId=654) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@panchenko Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=654)!

**Comment by rwinch** [comment]
Thanks for the PR @panchenko! This is now merged via 1c9dfa663851673404eacda8ce99773d33ea1113 and I polished it via 25aec9935759638412fade92e7a0736322fcd33e

**Comment by panchenko** [comment]
@rwinch The last part is slightly not nice in byte code, if you care :-)

In the first case it's just `ldc`, in the other that's done via a synthetic method containing `getstatic`.
During execution it should be optimized anyway, but still more work for the JVM :-)

**Pull request closed without merging**
