### PR TITLE
Remove unnecessary JedisConnectionFactory bean

### PR DESCRIPTION
**Pull request by roykachouh**
Fixes issue #102

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR!

Unfortunately, this doesn't quite resolve the issue since we need to ensure that our documentation is updated. Specifically the [docs/src/docs/asciidoc/guides/boot.adoc](https://github.com/spring-projects/spring-session/blob/ba07c1d5620f290eb5ee8a853c748019182d8345/docs/src/docs/asciidoc/guides/boot.adoc) needs to update the [Spring Configuration](http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/boot.html#boot-spring-configuration) section to remove the <2>. It would be good to replace it with something like:

```
NOTE: Spring Boot automatically creates ... In a production environment you need to ensure to configure your JedisConnectionFactory bean to point to your Redis instance. <insert link to how to configure>
```

Would you mind updating the PR to contain the documentation updates too? Afterwards I can merge the PR.

Thanks again!

**Comment by roykachouh** [comment]
Hey @rwinch, I updated the docs...I will make sure to check them in future PR's.

**Comment by rwinch** [comment]
Thanks for updating the PR! Your commits afc3752b33227e3dfacbf26f90522571eea57814 37aafc51480e12f2742843810e0b205cd45632d5 are now merged into master.

NOTE: I ended up adding a [little polish](https://github.com/spring-projects/spring-session/commit/3f2364312132b65fa12841e7392a01bf38d361c3) to the documentation. Feel free to review and provide any feedback you might have.

**Comment by roykachouh** [comment]
Looks good @rwinch! I look forward to helping out more on this project.

**Pull request closed without merging**
