### PR TITLE
Delay allocating Strings for Redis keyspace notifications

### PR DESCRIPTION
**Pull request by theigl**
### Problem

Spring Session Redis allocates new Strings for `channel` and `body` of all incoming messages. In my case, Redis is used to store other session related data and `RedisIndexedSessionRepository` receives a lot of key expiration and deletion messages that it doesn't need to handle. Hundreds of megabytes of Strings are allocated unnecessarily every minute.

In such a case, it makes sense to delay allocating new Strings until we are sure the message should be handled by Spring session.

### Solution

This PR directly uses the message's `byte[]` to check if a message should be handled. String allocation is delayed until we know that the message is intended for Spring Session.

### CODE REVIEW

**Comment by theigl** [comment]
I also created a related PR in Spring Data Redis that can further reduce the allocation rate for messages that should be handled by Spring session:

https://github.com/spring-projects/spring-data-redis/pull/559

**Review by vpavic — APPROVED** [review]
This looks like a nice optimization to me @theigl. :+1:

**Comment by theigl** [comment]
@vpavic: I have a version of this in production already and it saves a couple of hundred MB of string allocations a minute. Our Redis is not really busy so this might make even more of a difference for other users. 

Unfortunately, this is only half of the story because {{Message.getChannel()}} and {{Message.getBody()}} create new byte arrays. So filtering incoming messages is still not allocation free even after merging this PR. But it is a step in the right direction.

I'll ping the Spring Data guys to see if there is a chance my other PR will get merged. With both PRs applied, message filtering wouldn't allocate at all.

**Comment by theigl** [comment]
@vpavic: I discussed the situation with @mp911de and there is not much that can be done to improve the situation on the Spring Data side. So please go ahead and merge this PR if it is OK with you.

**Pull request merged**
