### PR TITLE
Fix ClassCastException Token$Tombstone 

### PR DESCRIPTION
**Pull request by jxblum**
Fixes for gh-373

### CODE REVIEW

**Comment by rwinch** [comment]
@jxblum Thanks for the PR! I'm not sure we want to modify the samples to use GemFire. We can always add more samples but we do not want to change the existing samples.

**Comment by jxblum** [comment]
@rwinch you can discard the commits for the changes to the Security/Users samples.  Or, it maybe nice to include different configurations for _Spring Session's_ supported stores and provide instructions on how to change stores when running the samples.  Of course, the default could be to use Redis and preserve the work you have already done.  Either way; no worries.

**Comment by rwinch** [comment]
@jxblum Thanks. I just wanted to make sure I wasn't missing something. I will just use ee38337

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master via 53d7c84f73be1df4d

**Pull request closed without merging**
