### PR TITLE
Fix Redis session expiration entry deletion

### PR DESCRIPTION
**Pull request by swurzinger**
fixes redis session expiration entry deletion

see #1799 for details

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@swurzinger Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=1800)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-session&pullRequestId=1800) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@swurzinger Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=1800)!

**Review by eleftherias — CHANGES_REQUESTED** [review]
Thanks for the PR @swurzinger!
I have a few requests before I merge this:
1) Please update the Apache license header to go up to the year 2021 in the modified files
2) Please add `Closes gh-585` to your commit message so that it is automatically linked to the reported issue

**Comment by swurzinger** [comment]
updated license header and commit message as requested

**Comment by eleftherias** [comment]
Thanks @swurzinger! This is now merged into master.

**Pull request merged**
