### PR TITLE
Allow configuring cookie expiration in CookieHttpSessionStrategy

### LINKED ISSUE #106: Allow configuring cookie expiration in CookieHttpSessionStrategy
While a secure default is important (i.e. having a cookie expire when browser is closed), some applications may want to customize this. We should allow customizing the cookie expiration.

Relates to #112

### PR DESCRIPTION
**Pull request by llambda**
Fixes #106

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the quick PR!

We want to ensure to include tests for every code change. Can you add a few tests to CookieHttpSessionStrategyTests?

**Comment by llambda** [comment]
Sure, I can certainly add some docs. By the way I added a test to the commit.

**Comment by rwinch** [comment]
Thanks! Once we get the updated docs I can double check everything and merge the PR. Thanks again!

**Comment by manderson23** [comment]
Hey @llambda any progress on the docs? I'm just in the middle of porting an application to Spring Session that requires a max age on the cookie.

**Comment by llambda** [comment]
Sorry, I haven't had time to work on it yet. Also I noticed gradle doc generation fails with Java 8 saying "FAILURE: Build failed with an exception"

**Comment by manderson23** [comment]
I could maybe provide a PR with the required documentation changes to get this merged if @rwinch could provide guidance on the level of detail required. Is something like the following enough? OR do you also want code samples?

## Cookies

[CookieHttpSessionStrategy](http://docs.spring.io/spring-session/docs/current-SNAPSHOT/api/org/springframework/session/web/http/CookieHttpSessionStrategy.html) provides the mechanism for overriding default values of the cookie associated with the HTTP session.

The following values are configurable.

* __Name__ - The name of the cookie. The default value is SESSION.
* __Maximum Age__ - The maximum age of the cookie in seconds. This value has the same behaviour as [javax.servlet.http.Cookie.setMaxAge](http://docs.oracle.com/javaee/7/api/javax/servlet/http/Cookie.html#setMaxAge%28int%29) The default value is -1.

**Comment by manderson23** [comment]
Any comments on my suggestion re documentation for getting this merged?

**Comment by rwinch** [comment]
@manderson23 Thanks for offering to document this! There does not need to be a sample application, but I think we should have an example of how to customize it in both XML and Java configuration within the reference. Please note that all code should be tested too. You will find the code from the reference is in [docs/src/test/java/docs|https://github.com/spring-projects/spring-session/tree/master/docs/src/test/java/docs] and then the reference includes the code that has been tested.

**Comment by manderson23** [comment]
@rwinch given the code requirement how would a pull work? Do I need to fork @llamba repo and work/create a pull against that? If i fork the main repo I assume my build would fail until this pull was merged.

**Comment by rwinch** [comment]
@manderson23 Thanks for the fast response! Go ahead and create a new PR with multiple commits (i.e. one from @llambda and one from yourself with the additions). Once we accept the other PR we can close this one.

**Comment by rwinch** [comment]
Thanks for the great request! I'm trying to aggregate all the feature requests for cookies, so we can solve this problem more holistically. Therefore, I'm closing this in favor of #299 which takes this feature into account.

**Comment by llambda** [comment]
Thanks @rwinch , appreciate your hard work on this.

**Pull request closed without merging**
