### PR TITLE
Replace put of IMap [Hazelcast]

### PR DESCRIPTION
**Pull request by dhawani**
Based on [article](https://blog.hazelcast.com/performance-top-5-1-map-put-vs-map-set), replace put with set to avoid serialisation and de-serialisation of entires.

### CODE REVIEW

**Comment by vpavic** [comment]
Thanks for the PR @dhawani.

Personally I'd keep using the existing `IMap` operation for consistency. As you've discovered yourself while trying to also replace the use of `IMap#remove` with `IMap#delete`, these operations are breaking some of the listener contracts as stated in the javadoc:

> This method breaks the contract of EntryListener. When an entry is updated by set(), it fires an EntryEvent with a null oldValue.

Even though `IMap#set` works within `HazelcastSessionRepository` I can see some users relying on `EntryListener` contract.

Do you have any opinion on this @rwinch?

**Comment by vpavic** [comment]
@dhawani We've discussed this internally a bit and we would make the use of `IMap`s `set` and `delete` operations optional for users. That is, `HazelcastSessionRepository` would have a flag that would allow user to switch to `set`/`delete` operations (with default being existing ones, `put`/`remove`). Note that when using `set`/`delete` session event publishing would be disable.

Are you willing to rework you PR to do that?

**Comment by dhawani** [comment]
@vpavic I have made this change based on the flag. 

Instead of disabling the event entirely, i am passing what all is available. In case of create event there is no change at all. In case of destroy and expire, the old value isn't available. But still we are able to pass the event. Then it becomes user's choice to subscribe to it. 

In the application where i am using this, I am only interested for create.  

Take a look at it and let me know if there are any more changes required.

**Comment by vpavic** [comment]
Thanks for the update @dhawani - will provide some feedback after I take a closer look.

**Comment by dhawani** [comment]
@vpavic Any update on this ?

**Comment by vpavic** [comment]
@dhawani This will be addressed as a part of one of the upcoming 2.0 milestone releases. Most of our focus currently is with reactive support and some breaking changes we plan to introduce as a part of 2.0.

**Comment by vpavic** [comment]
I'm putting this on hold as we're looking to use Hazelcast's `EntryProcessor` for write operations - see #850. We can revisit once that's done.

**Comment by vpavic** [comment]
Thanks for the PR @dhawani, however we've addressed this as a part of #850 in f5912da. Check out [this comment](https://github.com/spring-projects/spring-session/issues/850#issuecomment-346894660) for more details.

Note that we've kept `IMap#remove` for session removal due to event considerations.

**Pull request closed without merging**
