### PR TITLE
Add SessionExpiredEvent and SessionDeletedEvent

### PR DESCRIPTION
**Pull request by manderson23**
Implements #257 

Let me know if I've missed anything particularly documentation and tests.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! It seems we should come up with a similar event for deleting sessions (i.e. SessionDeletedEvent). Thoughts?

**Comment by manderson23** [comment]
So SessionDestroyedEvent would be a base class (abstract?) with specific expired and deleted subclasses?

**Comment by rwinch** [comment]
@manderson23 That is correct. This would allow receiving either specific event. To me it seems if we allow receiving only expired events users should also be able to only receive deleted events.

**Comment by manderson23** [comment]
Sounds reasonable. Shouldn't be much more work.

**Comment by manderson23** [comment]
Further doc updates still to follow.

**Comment by manderson23** [comment]
@rwinch that should be SessionDeletedEvent complete. Let me know if there are any issues.

**Comment by rwinch** [comment]
Thanks for the PR! This is merged into master and will be a part of 1.1. I did some very minor polish in https://github.com/spring-projects/spring-session/commit/7518306975f99e5d3095fc6ab6b19aefd0f790b8 but other than that it looked good.

You will note I have also added a `SessionCreatedEvent` #261 to support `HttpSessionListener` #4. I had to do some merging to get that to work with your changes. So you may want to give the snapshot a try and see if it is working for you to double check me :)

**Pull request closed without merging**
