### PR TITLE
Support for Neo4j

### PR DESCRIPTION
**Pull request by espiegelberg**
I’m implementing Neo4j support for Spring Session.

The new OgmSessionRepository and related classes are modeled closely after the JdbcOperationsSessionRepository but are altered to make use of Neo4j.

The OgmSessionRepositoryITests (_currently_ disabled with an @Ignore because it requires a local instance of Neo4j to be available), is not yet as complete as other database implementations test suites but demonstrates that my code is functional. This test can be executed while a Neo4j instance is running locally by removing the @Ignore.

My next steps are to improve and polish the code, update JavaDocs, add the corresponding unit and integration test coverage to match the other database (JDBC, Redis, etc.) implementations, format the code to match the project style as close as possible, and to create a spring-session-sample-javaconfig-neo4j sample.

Because this is a non-trivial PR and the above items are a sizable effort, I’ve decided to create this PR and ask for review and feedback early, in parallel to  embarking on the above items, in the hope that the early feedback can be incorporated as part of the above activities rather than after the fact.

Please review this PR and, while recognizing that this PR is a work in progress, provide any feedback that helps improve it and boosts its chances being accepted.

### CODE REVIEW

**Comment by vpavic** [comment]
Thanks for the PR @espiegelberg.

Please note that we're limiting the `SessionRepository` implementations provided by Spring Session project to Redis, JDBC and Hazelcast. The background behind this was explained in #768 and [this blog post](https://spring.io/blog/2017/05/11/spring-session-2-0-0-m1-released).

We do however encourage you to make this effort a Spring Session community extension project. We promote such extensions in [Community Extensions](http://docs.spring.io/spring-session/docs/2.0.0.BUILD-SNAPSHOT/reference/html5/#community-extensions) section of the reference manual so please open a issue/PR to list your project in there once you set it up.

You can also use the newly created [spring-session-data-mongodb](https://github.com/spring-projects/spring-session-data-mongodb) and [spring-session-data-geode repositories](https://github.com/spring-projects/spring-session-data-geode) as references.

**Comment by vpavic** [comment]
Closing for reasons explained in the previous comment.

@espiegelberg Let us know if you decide to make this a community extension project.

**Comment by espiegelberg** [comment]
@vpavic Yes, I will create this as a community extension project, using spring-session-data-mongodb and spring-session-data-geode repositories as samples/references. Because I don't have access to the spring-projects repo, I plan to use my github account, as they did with spring-session-orientdb, and will open a new item when I have it ready for review. 

Is this a reasonable approach?

**Comment by vpavic** [comment]
Thanks for the feedback @espiegelberg - the approach is correct.

**Pull request closed without merging**
