### PR TITLE
Add Apache Ignite integration module 

### PR DESCRIPTION
**Pull request by SammyVimes**
Apache Ignite is a Distributed In-Memory Computing Platform with one of the top-10 most active Apache Communities.
Although there are a couple of third-party spring-session integrations, I think Apache Ignite deserves out of the box support (disclaimer: I'm Apache Ignite Contributor) as it's being actively developed and a lot of new features that can improve the performance of web-application are being continuously added. Also, MapSessionRepository won't be able to use ignite-indexing (that's a module for fast querying of cache), and this issue (and other problems) is addressed in this pull request.

### CODE REVIEW

**Comment by eleftherias** [comment]
Thanks @SammyVimes!

This looks good and I think it is well suited for it's own module and GitHub repo.

We like to keep the Spring Session data store implementations separated.
Firstly, this allows those with in-depth knowledge of the data store to maintain the module, rather than depending on the Spring Session committers who are not experts in that technology. 
Secondly, it allows the module maintainers to work independently.

You can see an in-depth explanation in gh-768.

Once the Apache Ignite module is ready, we can add it to the Spring Session release train (see https://github.com/spring-projects/spring-session-bom).

If you're interested in an example, we're already doing this with https://github.com/spring-projects/spring-session-data-geode and it is working well.

**Comment by vpavic** [comment]
I agree that this is a candidate for community managed project, rather than being managed here, exactly for the reasons outlined above. If this ever materializes as a community project, ping us back so that we can add it to [the list of community modules we have in reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#community-extensions).

Also note that we've had inquiries about Apache Ignite several times in the past - see #660, #732 and #1091. So this is effectively a duplicate of #660.

> Once the Apache Ignite module is ready, we can add it to the Spring Session release train (see https://github.com/spring-projects/spring-session-bom).

We shouldn't do this. There's no guarantee that community managed Spring Session modules would see continuos support and as such present a significant risk to the release of Spring Session BOM. When we were putting together the BOM module, rule of thumb was that Spring Session modules managed within the [`spring-projects`](https://github.com/spring-projects) org are included in the BOM, while community ones are promoted using mentioned listing in the reference manual.

**Comment by SammyVimes** [comment]
Hello @eleftherias! What my next steps should be, if I want this module to be part of the release train? As I can see [here](https://github.com/spring-projects/spring-session/issues/768), module maintainer must be a Spring committer, right?

**Comment by eleftherias** [comment]
@SammyVimes Yes, that's right. Sorry about the miscommunication.
For release coordination, we would want the maintainer to be a Spring committer in order to include the module in the BOM.

We do however encourage you create a Spring Session community extension project. As mentioned above, we promote such extensions in Community Extensions section of the reference manual.

The first steps are to create a GitHub repository, documentation and an artifact for Spring Session Apache Ignite.

Once you have set that up, please open an issue/PR to list your project in the reference manual.

**Comment by pauldanckaert** [comment]
I was looking to use Apache Ignite with Spring Session, and this implementation would seem to fit that need. Was this ever extracted into a community module? I can't find any reference to it, and it seems to be stuck in this triage state at the moment.

**Comment by eleftherias** [comment]
@pauldanckaert No, it has not been extracted into a community module.

**Comment by eleftherias** [comment]
Closing this PR, as per the discussion above. In summary, this is a great candidate for a community extension project and would be best suited for it's own repository.

**Pull request closed without merging**
