### PR TITLE
Suggested changes for compatibility with hazelcast:4.0.1 and spring-boot:2.3.0 on the branch 'v2.3.x' 

### PR DESCRIPTION
**Pull request by adeniyiodunlami**
Suggested changes for compatibility with hazelcast:4.0.1 and spring-boot:2.3.0. 
#1644 
gh-1584

### CODE REVIEW

**Comment by vpavic** [comment]
> we will create a new class, similar to `HazelcastIndexedSessionRepository` that is compatible with Hazelcast 4.

I'd suggest against this approach, as it will inevitably result in:

- duplicated code
- `SessionRepository` component that's bound to be deprecated once Hazelcast 4 is baseline
- more difficult configuration

IMO a better way to tackle this would be to extract a strategy that encapsulates the use of Hazelcast API's that introduced binary incompatible changes between Hazelcast `3.x` and `4.x` - `HazelcastIndexedSessionRepository` would internally implement this strategy to keep the existing (Hazelcast `3.x` compabile) behaviour while additional implementation would be provided to support Hazelcast `4.x`.

Once Hazelcast `4.x` is the baseline (likely Spring Session `3.0`) those implementations simply switch places.

**Comment by pivotal-issuemaster** [comment]
@adeniyiodunlami Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=1645)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-session&pullRequestId=1645) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@adeniyiodunlami Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=1645)!

**Comment by eleftherias** [comment]
As discussed in the associated issue gh-1644, changes to support Hazelcast 4 were introduced via 2b6489c.
For that reason I'm closing this issue as a duplicate.

**Pull request closed without merging**
