### PR TITLE
Add Grails 3 Sample

### PR DESCRIPTION
**Pull request by erichelgeson**
First 1/2 of #246

Shows example of session integration along with spring security core plugin integration.

### CODE REVIEW

**Comment by rwinch** [comment]
@erichelgeson Thanks for submitting this!

I'll wait for the second half before merging/reviewing in detail. One thing we will want to ensure we have is some tests to ensure this is working.

**Comment by erichelgeson** [comment]
No problem, took a first stab at the docs too (could use a second set of eyes on that as well).

**Comment by erichelgeson** [comment]
@rwinch tests adapted from the spring boot example. Can be run by `./gradlew integrationTest`

**Comment by rwinch** [comment]
@erichelgeson Thanks for the updates!

Some feedback.

* We should add this project to settings.gradle

```
include 'samples:grails3'
```

* The build is not currently passing. I get the following error:

```
:integrationTest

sample.HomeSpec > Anonymous page not redirected to login FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException
            Caused by: java.lang.IllegalStateException
```

* Perhaps we can change test/index to be the index at the context root so users don't have an additional step.

**Comment by erichelgeson** [comment]
The tests are passing, just I didn't have a random port assigned (the boot example didnt work in grails, but i found one that does). the root `/` is not protected, then `/test/` is a protected resource in the tests. I think it's valuable to leave both tests in (anon ok and anon redirect)

Pushed up the changes, let me know!

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master. I have applied a bit of polish via 3825a46418358a9b807f5ef9a8d8d2ba095fadd1

**Pull request closed without merging**
