### PR TITLE
Upgrade testcontainers to 1.12.2

### PR DESCRIPTION
**Pull request by candrews**

### CODE REVIEW

**Comment by vpavic** [comment]
The upgrade to Testcontainers `1.12.2` (or `1.12.1` for that matter) was deliberately skipped for `2.2.0.RC1` due to issue with our Hazelcast client-server integration, as can be seen from the failing build.

**Comment by bsideup** [comment]
Hi @vpavic,

Any idea why it started failing with 1.12.1+?

Let me know if you need help to debug it

**Comment by vpavic** [comment]
Thanks @bsideup. In midst of release rush, I didn't have time to take a closer look at the problem, but I plan to do so soon and will report to Testcontainers issue tracker, if needed.

**Comment by vpavic** [comment]
This was resolved via #1527.

**Pull request closed without merging**
