### PR TITLE
Commit Session on Include Dispatch calls commitSession each time

### PR DESCRIPTION
**Pull request by laurentschoelens**
This provides a fix proposal for https://github.com/spring-projects/spring-session/issues/2284

It marks the current request that a first-commit has been done in a include context to not commit on every requestDispatcher.include call

### CODE REVIEW

**Comment by laurentschoelens** [comment]
Tested successfully on my app.

Before fix, JFR results :
image

After fix, JFR results :
image

**Comment by laurentschoelens** [comment]
I've not been able to run all tests on my laptop and not found information on how to do it on documentation.

**Comment by marcusdacoregio** [comment]
Hi @laurentschoelens, we are gonna consider this as an enhancement since the code is running as expected and this is a performance enhancement. Can you rebase your branch off of `main` and also add a test to make sure the session is not committed again? Ideally, the test should fail without your changes and pass with them.

**Comment by laurentschoelens** [comment]
Hi @marcusdacoregio  : hope done well :)
I've added one unit test that fails with actual code and pass with my changes.
Since Spring 2.7 is still in maintenance, could I hope to have it backported to latest 2.X branch ?

**Comment by laurentschoelens** [comment]
@marcusdacoregio seen that build failed due to checkstyle violation on my new unit test 😔

**Comment by marcusdacoregio** [comment]
Don't worry @laurentschoelens, I can take care of it before merging

**Comment by marcusdacoregio** [comment]
Thanks @laurentschoelens, this is now merged into `main` via https://github.com/spring-projects/spring-session/commit/7360723583112b9d3f1fc9b02d45e7509124e65d with this polish commit https://github.com/spring-projects/spring-session/commit/2d43c31e67623e8dc48b5ac008d46d18aa190bf9

**Pull request closed without merging**
