### PR TITLE
Extends classes

### PR DESCRIPTION
**Pull request by oassuncao**
- Extract SessionRepositoryRequestWrapper and SessionRepositoryResponseWrapper to a public class
- Created methods to override wrapRequest and wrapResponse
- Changed private fields to protected to override configuration
- Changed RedisSession to override RedisOperationsSessionRepository
(cherry picked from commit eb0eb63)

### CODE REVIEW

**Comment by rwinch** [comment]
@oassuncao Thanks for the PR! A few things...

* Looks like there is a duplicate submission #409
* This makes a lot of changes without explanations as to why they need changed. 
  * Can you elaborate on why the changes are necessary?
  * We can then determine which changes should be merged and break the issues up into distinct issues and commits.

**Comment by oassuncao** [comment]
Hi @rwinch 

This pull request is about master branch the submission #409 (1.1.x) 

Today if the developer need to customize SessionRepositoryFilter or RedisOperationsSessionRepository it's impossible. The developer need to rewrite all code of this classes

In my case I have 2 Sessions
1- Main Session (Security, etc)
2- App Session (My application can have many apps)

**Comment by rwinch** [comment]
@oassuncao First...should #409 be closed as a duplicate? I don't think I understood your response.

Second I need more details on what you are trying to solve.

**Comment by rwinch** [comment]
@oassuncao I now understand that #409 is against 1.1.x. I close that PR since we are only accepting bug fixes for 1.1.x.

**Comment by oassuncao** [comment]
I've a application named CEAP that user can create many sub-application named (CustomApp)

Every CustomApp have a different classes and one ClassLoader. I need to have different Session per CustomApp.

1- CEAP Session (Principal, basic information)
2..x - CustomApp Session (One session per CustomApp)
  - Different redisNamespace 
  - Different RedisSerializer (other ClassLoader)
  - This session only have objects of CustomApp

```
public class CustomRootSessionRepositoryFilter<S extends ExpiringSession> extends SessionRepositoryFilter<S> {
// --------------------------- CONSTRUCTORS ---------------------------

    public CustomRootSessionRepositoryFilter(SessionRepository<S> sessionRepository) {
        super(sessionRepository);
    }

// -------------------------- OTHER METHODS --------------------------

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        String customRootName = CustomRootUtils.getCustomRootName(request.getRequestURI());
        if (StringUtils.isEmpty(customRootName)) {
            filterChain.doFilter(request, response);
            return;
        }

        super.doFilterInternal(request, response, filterChain);
    }

    @Override
    protected SessionRepositoryRequestWrapper wrapRequest(HttpServletRequest request, HttpServletResponse response) {
        SessionRepositoryRequestWrapper<S> sessionRepositoryRequestWrapper = new SessionRepositoryRequestWrapper<>(request, response, servletContext, sessionRepository, httpSessionStrategy);
        sessionRepositoryRequestWrapper.setSessionAttribute("CustomSessionRepositoryRequestWrapper");
        sessionRepositoryRequestWrapper.getSession();
        return sessionRepositoryRequestWrapper;
    }
}
```

Created sessionAttribute field to change the name of Session Objetcs attribute, to don't get objetcs of CEAP Session. This filter run before the Custom App run.
`sessionRepositoryRequestWrapper.setSessionAttribute("CustomSessionRepositoryRequestWrapper");`


````
public class CustomRedisOperationsSessionRepository extends RedisOperationsSessionRepository {
// --------------------------- CONSTRUCTORS ---------------------------

    public CustomRedisOperationsSessionRepository(RedisConnectionFactory redisConnectionFactory) {
        super(redisConnectionFactory);
    }

    public CustomRedisOperationsSessionRepository(RedisOperations<Object, Object> sessionRedisOperations) {
        super(sessionRedisOperations);
    }

// ------------------------ INTERFACE METHODS ------------------------


// --------------------- Interface SessionRepository ---------------------

    @Override
    public RedisSession getSession(String id) {
        RedisSession redisSession = super.getSession(id);
        if (redisSession == null)
            redisSession = new RedisSession(new MapSession(id));
        return redisSession;
    }
}
```

I override method getSession to get the CustomApp Session, if the session is null, I created a new RedisSession empty with the same sessionId. If I don't override this method, the code will create a new session with a different sessionId and changed the cookie.

**Comment by oassuncao** [comment]
My commit only open possibility to extended redis repository, override methods and can change the wrap request or response with other classes without rewrite many, many code

Thanks

**Comment by rwinch** [comment]
@oassuncao Thanks for the response.

From what I understand, you can do this without any changes to Spring Session. You can create a new instance of `SessionRepositoryFilter` for each "CustomApp". The "CustomApp" `SessionRepositoryFilter` will only intercept requests for the specific "CustomApp" by either changing the servlet mappings or using something like Spring Security's `DelegatingFilterProxy`.

My concern about the proposed changes is that this appears to be a bit of an edge case. While I understand why you need these changes, I don't want to make the code more complicated for the 95% case. As outlined above, I think you can fairly easily achieve this without changes. For these reasons, I'm closing this as won't fix.

If you have additional questions on getting this working, please don't hesitate to reach out on StackOverflow (preferred) or GitHub issues. 

PS: If you don't get a response on StackOverflow (you should) within a day or so, feel free to ping us via GitHub issues.

**Comment by oassuncao** [comment]
Hi @rwinch 

I do this, I have 2 filters

1- CEAP (SessionRepositoryFilter)
2- CustomApp (CustomSessionRepositoryFilter)

But when the second filter run, the filter get the session of CEAP, because we have today this code below on SessionRepositoryFilter.java

Class SessionRepositoryRequestWrapper

```java
@Override
		public HttpSessionWrapper getSession(boolean create) {
			HttpSessionWrapper currentSession = getCurrentSession();
			if(currentSession != null) {
				return currentSession;
			}
                        ...
               }
```

The method getCurrentSession it's a cache that put the session on request.
```java
               private void setCurrentSession(HttpSessionWrapper currentSession) {
			if(currentSession == null) {
				removeAttribute(CURRENT_SESSION_ATTR);
			} else {
				setAttribute(CURRENT_SESSION_ATTR, currentSession);
			}
		}
```

To change the CURRENT_SESSION_ATTR, I created a field named sessionAttribute, to have on the Request more than one session on "cache"

`sessionRepositoryRequestWrapper.setSessionAttribute("CustomSessionRepositoryRequestWrapper");`

**Comment by rwinch** [comment]
@oassuncao You should only invoke `SessionRepositoryFilter` on requests that are not `CustomSessionRepositoryFilter`.

**Pull request closed without merging**
