### PR TITLE
Add support for custom Prefix

### LINKED ISSUE #597: Allow custom Redis namespace prefix
Allow customization of Default Redis Namespace.

e.g.: `spring:session:` to `foo:bar:`.

Currently `spring:session:` is hardcoded

The scenario is that i currently have multiple services that will consult the Session Data within Redis and i don't want the Namespace to begin with `spring:session:`

Even if i customize it through `@EnableRedisHttpSession(redisNamespace = "foo")` i still get `spring:session:foo` instead of `foo`.

I suggest creating an extra property on the Annotation like `defaultPrefix` to set this value, that defaults to `spring:session:`

### PR DESCRIPTION
**Pull request by driverpt**
This closes #597

### CODE REVIEW

**Comment by driverpt** [comment]
Any feedback on this ?

**Comment by vpavic** [comment]
@driverpt Thanks for the PR. We'd prefer a simpler approach where `RedisOperationsSessionRepository#setRedisKeyNamespace` would configure the entire namespace, not just the part of it. Are you willing to update the PR in that direction?

**Comment by driverpt** [comment]
What do you mean with "entire namespace"?

**Comment by vpavic** [comment]
Sorry for not being clear enough.

With the current state, invoking `RedisOperationsSessionRepository#setRedisKeyNamespace` with `test` will result in `spring:session:test:` namespace. It would be more straightforward if this resulted in `test:` namespace. This would be much simpler and I believe it would address your concern from #597.

**Comment by driverpt** [comment]
@vpavic , the only reason i haven't changed ```RedisOperationsSessionRepository#setRedisKeyNamespace``` behaviour was to maintain backwards compatibility.
It's highly possible that you have systems relying on this behaviour, and changing it might cause an "earthquake".
I can change the code, but it may cause backwards-compatibility problems.

**Comment by vpavic** [comment]
@driverpt 2.0 is our chance to make such change, together with other non-passive one we have already prepared for the new major release.

**Comment by driverpt** [comment]
@vpavic , ok, i'll change this PR. But i need to rebase it against 2.0 branch

**Comment by vpavic** [comment]
Thanks! Note that the target branch is still `master`.

**Comment by driverpt** [comment]
@vpavic , created a new PR. #919

**Pull request closed without merging**
