### PR TITLE
Allow configuring cookie expiration in CookieHttpSessionStrategy with documentation

### PR DESCRIPTION
**Pull request by manderson23**
#107 with the requested documentation.

@rwinch please let me know if anything needs changed.

### CODE REVIEW

**Comment by manderson23** [comment]
@rwinch just wondering if you are planning to merge this for 1.0.1? Or do you plan to go with #162?

I noticed that there are conflicts with this pull so I'd be happy to update and fix them if you are going to use it.

**Comment by rwinch** [comment]
@manderson23 Thanks for the reply. We will likely support both mechanisms. #162 will likely just be a way to update the properties on CookieHttpSessionStrategy.

Since this is not a bug fix, it will be in the next feature release (i.e. 1.1 M1).

**Comment by manderson23** [comment]
@rwinch what is the current schedule for 1.1M1? Shall I leave this in a conflicted state for now then until a time comes when it may be merged?

**Comment by rwinch** [comment]
@manderson23 I don't yet have a schedule for M1, so I would leave the PR as is for now. When the time comes, I can merge the changes for you since it is technically "my fault". Alternatively, if you like I can ping you when I have 1.1 M1 planned and you can fix them.

**Comment by manderson23** [comment]
@rwinch are you planning to use this PR for 1.1? If so I'd be happy to update it to remove the conflicts.

**Comment by rwinch** [comment]
@manderson23 Thanks for reaching out.

I'm certainly thinking we need to do something with allowing for additional cookie attributes to be specified by the user for 1.1. However, I'm not quite certain how we best want to do that. You will see that #162 is providing similar functionality.

So the answer is...I'd wait to remove the conflicts till we decide what we want to do.

**Comment by manderson23** [comment]
OK. As long as it gets into 1.1. somehow I'll be happy!

**Comment by rwinch** [comment]
This was resolved as part of #299

**Comment by rwinch** [comment]
See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html for details.

**Pull request closed without merging**
