### PR TITLE
Add Spring Session Data GemFire with Spring Boot sample

### PR DESCRIPTION
**Pull request by jxblum**
Hi @rwinch 

I know you gave me commit privileges now (thank you) but wanted to give you an opportunity for review and coordinate these changes with the `1.2.1.RELEASE` before this PR is merged.

If you have any questions, let me know.

Thanks,
John

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jxblum Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=549)!

**Comment by vpavic** [comment]
@jxblum Preferably, you'd use webjars for client-side web libs, see #454 and #491 for some examples.

**Comment by pivotal-issuemaster** [comment]
@jxblum Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session&pullRequestId=549)!

**Comment by jxblum** [comment]
@rwinch and @vpavic `Spring Boot` WebJars support added to the `httpsession-gemfire-boot` sample as requested.

@rwinch let me know if you have any other feedback; if not I (or you) can merge this if approved.

Thanks!

**Comment by rwinch** [comment]
Thanks for the PR! This is merged into master with a little polish via 808a5503438e0949d0e5cb209817534870bc95b5

**Pull request closed without merging**
