### PR TITLE
Eliminate unnecessary sessionRepository::findById

### PR DESCRIPTION
**Pull request by quaff**
It is an obvious fix.

### CODE REVIEW

**Comment by eleftherias** [comment]
Hi @quaff, this is a duplicate of gh-1732.
Please use the search functionality to check for existing issues before opening a new issue or pull request.

**Comment by quaff** [comment]
@eleftherias This one is more simple and safe than that one.

**Comment by quaff** [comment]
@vpavic Could you take a look at this?

**Comment by vpavic** [comment]
After a closer review, we've decided to do this change in `3.0.0-RC1` as it is an elegant way of removing that extra round trip to session store and fetch the session. Thanks for the contribution @quaff.

**Pull request closed without merging**
