### PR TITLE
Use webjars for static resources in sample apps

### LINKED ISSUE #458: Use Webjars in samples

### PR DESCRIPTION
**Pull request by vpavic**
This resolves #458.

- [X] I have signed the CLA

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! Unfortuantely, the changes do not work for the non-boot applications. For example, the [Spring Security sample](https://github.com/vpavic/spring-session/blob/gh-458/samples/security/build.gradle) returns a 404 for the webjars URL.

**Comment by vpavic** [comment]
Hmm, interesting. I've ran all the examples (well, except Gemfire-based ones) before submitting the PR.
Will look into it, possibly something got cached on my side.

**Comment by rwinch** [comment]
Thanks for the response. 

A note...this is lower priority than #495 since this is just samples (I can merge this even in a patch release)

**Comment by vpavic** [comment]
@rwinch I've updated the PR.

Issue was that the links to static resources were not aware of the context path. This is now fixed and tested.

**Comment by vpavic** [comment]
@rwinch Is there anything more you need me to do on this, considering the PR is still labeled as ```waiting for feedback```?

**Comment by rwinch** [comment]
@vpavic Thanks for the nudge! It was me dropping the ball on removing the label. I have updated the ticket (but still need to take a look at it).

**Comment by rwinch** [comment]
Thanks for the PR! Merged via 2b4a349b1a8710b47e89e412d3f1ab511e828323

**Comment by rwinch** [comment]
NOTE: I created #566 so that the samples are further improved to use webjars-locator

**Pull request closed without merging**
